version: '3'
services:
  api:
    build:
      context: .  
      dockerfile: api/Dockerfile  
    container_name: fastapi-api
    ports:
      - "8000:8000" 
    volumes:
      - ./model:/app/model
      - ./monitoring:/app/monitoring
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000" 
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: always
  
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge